export const GET_ALL_REVIEWS_REQUEST = 'GET_ALL_REVIEWS_REQUEST';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const GET_ALL_REVIEWS_FAILURE = 'GET_ALL_REVIEWS_FAILURE';

export const GET_REVIEWS_BY_ID_REQUEST = 'GET_REVIEWS_BY_ID_REQUEST';
export const GET_REVIEWS_BY_ID_SUCCESS = 'GET_REVIEWS_BY_ID_SUCCESS';
export const GET_REVIEWS_BY_ID_FAILURE = 'GET_REVIEWS_BY_ID_FAILURE';

export const ADD_REVIEWS_REQUEST = 'ADD_REVIEWS_REQUEST';
export const ADD_REVIEWS_SUCCESS = 'ADD_REVIEWS_SUCCESS';
export const ADD_REVIEWS_FAILURE = 'ADD_REVIEWS_FAILURE';

export const UPDATE_REVIEWS_REQUEST = 'UPDATE_REVIEWS_REQUEST';
export const UPDATE_REVIEWS_SUCCESS = 'UPDATE_REVIEWS_SUCCESS';
export const UPDATE_REVIEWS_FAILURE = 'UPDATE_REVIEWS_FAILURE';

export const DELETE_REVIEWS_REQUEST = 'DELETE_REVIEWS_REQUEST';
export const DELETE_REVIEWS_SUCCESS = 'DELETE_REVIEWS_SUCCESS';
export const DELETE_REVIEWS_FAILURE = 'DELETE_REVIEWS_FAILURE';
